version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "automerge"
    commit-message:
      prefix: "deps"
      prefix-development: "deps(dev)"
      include: "scope"
    reviewers:
      - "Shpota"
    allow:
      - dependency-type: "all"
    target-branch: "main"
    auto-merge: true
    auto-merge-settings:
      merge-strategy: "squash"
      strict: true
      delete-branch: true
    versioning-strategy: "auto"
    rebase-strategy: "auto"
